import type { ArtworkWithImages, ContactMessage, Order } from "../types";
import { defaultSiteSettings } from "../site";

const now = "2026-08-04T00:00:00.000Z";

export const demoArtworks: ArtworkWithImages[] = [
  {
    id: "demo-ink-current",
    slug: "demo-marker-study-current",
    title: "DEMO: Marker Study Current",
    subtitle: "Sample listing for layout testing",
    year: 2026,
    medium: "Marker",
    surface: "Paper",
    width_cm: 29.7,
    height_cm: 42,
    description:
      "Demonstration data only. Replace this placeholder with a real artwork before launch.",
    price_cents: 18000,
    currency: "EUR",
    status: "available",
    is_featured: true,
    is_published: true,
    manual_sort_order: 10,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-1",
        artwork_id: "demo-ink-current",
        object_key: "/sample-art/demo-marker-study-current.svg",
        alt_text: "Neutral demo placeholder for a marker artwork listing.",
        caption: "Demo placeholder image.",
        width: 1200,
        height: 1500,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-night-lines",
    slug: "demo-night-lines",
    title: "DEMO: Night Lines",
    subtitle: "Reserved sample listing",
    year: 2025,
    medium: "Marker and spray paint",
    surface: "Board",
    width_cm: 50,
    height_cm: 70,
    description:
      "Demonstration data only. Use this entry to test reserved-state presentation.",
    price_cents: 26000,
    currency: "EUR",
    status: "reserved",
    is_featured: false,
    is_published: true,
    manual_sort_order: 20,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: "2099-01-01T00:00:00.000Z",
    revolut_payment_url: "https://revolut.me/example-placeholder",
    images: [
      {
        id: "demo-img-2",
        artwork_id: "demo-night-lines",
        object_key: "/sample-art/demo-night-lines.svg",
        alt_text: "Neutral demo placeholder for a reserved artwork listing.",
        caption: "Demo placeholder image.",
        width: 1200,
        height: 1400,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-archive-piece",
    slug: "demo-archive-piece",
    title: "DEMO: Archive Piece",
    subtitle: "Sold sample listing",
    year: 2024,
    medium: "Marker",
    surface: "Paper",
    width_cm: 21,
    height_cm: 29.7,
    description:
      "Demonstration data only. Sold works remain visible as an archive.",
    price_cents: 12000,
    currency: "EUR",
    status: "sold",
    is_featured: false,
    is_published: true,
    manual_sort_order: 30,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-3",
        artwork_id: "demo-archive-piece",
        object_key: "/sample-art/demo-archive-piece.svg",
        alt_text: "Neutral demo placeholder for a sold artwork listing.",
        caption: "Demo placeholder image.",
        width: 1200,
        height: 1600,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
];

export const demoOrders: Order[] = [];
export const demoMessages: ContactMessage[] = [];
export const demoSettings = defaultSiteSettings;
