import type { ArtworkWithImages, ContactMessage, Order } from "../types";
import { defaultSiteSettings } from "../site";

const now = "2026-08-04T00:00:00.000Z";

export const demoArtworks: ArtworkWithImages[] = [
  {
    id: "demo-ink-current",
    slug: "demo-marker-study-current",
    title: "DEMO: Marker Study Current",
    subtitle: "Sample listing for layout testing",
    year: 2026,
    medium: "Marker",
    surface: "Paper",
    width_cm: 29.7,
    height_cm: 42,
    description:
      "Demo artwork entry for testing the gallery. Replace before launch.",
    price_cents: 18000,
    currency: "EUR",
    status: "available",
    is_featured: true,
    is_published: true,
    manual_sort_order: 10,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-1",
        artwork_id: "demo-ink-current",
        object_key: "/sample-art/demo-marker-study-current.svg",
        alt_text: "Demo image for a marker drawing listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1500,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-night-lines",
    slug: "demo-night-lines",
    title: "DEMO: Night Lines",
    subtitle: "Reserved sample listing",
    year: 2025,
    medium: "Marker drawings and spray-paint",
    surface: "Board",
    width_cm: 50,
    height_cm: 70,
    description:
      "Demonstration data only. Use this entry to test reserved-state presentation.",
    price_cents: 26000,
    currency: "EUR",
    status: "reserved",
    is_featured: false,
    is_published: true,
    manual_sort_order: 20,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: "2099-01-01T00:00:00.000Z",
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-2",
        artwork_id: "demo-night-lines",
        object_key: "/sample-art/demo-night-lines.svg",
        alt_text: "Demo image for a reserved artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1400,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-archive-piece",
    slug: "demo-archive-piece",
    title: "DEMO: Archive Piece",
    subtitle: "Sold sample listing",
    year: 2024,
    medium: "Marker",
    surface: "Paper",
    width_cm: 21,
    height_cm: 29.7,
    description:
      "Demonstration data only. Sold works remain visible as an archive.",
    price_cents: 12000,
    currency: "EUR",
    status: "sold",
    is_featured: false,
    is_published: true,
    manual_sort_order: 30,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-3",
        artwork_id: "demo-archive-piece",
        object_key: "/sample-art/demo-archive-piece.svg",
        alt_text: "Demo image for a sold artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1600,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-red-angle",
    slug: "demo-red-angle",
    title: "DEMO: Red Angle",
    subtitle: null,
    year: 2026,
    medium: "Marker drawings and spray-paint",
    surface: "Paper",
    width_cm: 30,
    height_cm: 40,
    description: "Demo artwork entry for testing the gallery. Replace before launch.",
    price_cents: 21000,
    currency: "EUR",
    status: "available",
    is_featured: true,
    is_published: true,
    manual_sort_order: 40,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-4",
        artwork_id: "demo-red-angle",
        object_key: "/sample-art/demo-marker-study-current.svg",
        alt_text: "Demo image for an available artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1500,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-green-room",
    slug: "demo-green-room",
    title: "DEMO: Green Room",
    subtitle: null,
    year: 2026,
    medium: "Marker",
    surface: "Paper",
    width_cm: 24,
    height_cm: 32,
    description: "Demo artwork entry for testing the gallery. Replace before launch.",
    price_cents: 15000,
    currency: "EUR",
    status: "available",
    is_featured: false,
    is_published: true,
    manual_sort_order: 50,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-5",
        artwork_id: "demo-green-room",
        object_key: "/sample-art/demo-night-lines.svg",
        alt_text: "Demo image for an available artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1400,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-orange-signal",
    slug: "demo-orange-signal",
    title: "DEMO: Orange Signal",
    subtitle: null,
    year: 2025,
    medium: "Marker drawings and spray-paint",
    surface: "Board",
    width_cm: 42,
    height_cm: 59,
    description: "Demo artwork entry for testing the gallery. Replace before launch.",
    price_cents: 24000,
    currency: "EUR",
    status: "available",
    is_featured: false,
    is_published: true,
    manual_sort_order: 60,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-6",
        artwork_id: "demo-orange-signal",
        object_key: "/sample-art/demo-archive-piece.svg",
        alt_text: "Demo image for an available artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1600,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-small-mark",
    slug: "demo-small-mark",
    title: "DEMO: Small Mark",
    subtitle: null,
    year: 2025,
    medium: "Marker",
    surface: "Paper",
    width_cm: 18,
    height_cm: 24,
    description: "Demo artwork entry for testing the gallery. Replace before launch.",
    price_cents: 9000,
    currency: "EUR",
    status: "available",
    is_featured: false,
    is_published: true,
    manual_sort_order: 70,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-7",
        artwork_id: "demo-small-mark",
        object_key: "/sample-art/demo-marker-study-current.svg",
        alt_text: "Demo image for an available artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1500,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-sold-line",
    slug: "demo-sold-line",
    title: "DEMO: Sold Line",
    subtitle: null,
    year: 2024,
    medium: "Marker",
    surface: "Paper",
    width_cm: 21,
    height_cm: 30,
    description: "Demo sold artwork entry for testing the gallery.",
    price_cents: 11000,
    currency: "EUR",
    status: "sold",
    is_featured: false,
    is_published: true,
    manual_sort_order: 80,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-8",
        artwork_id: "demo-sold-line",
        object_key: "/sample-art/demo-archive-piece.svg",
        alt_text: "Demo image for a sold artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1600,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
  {
    id: "demo-sold-spray",
    slug: "demo-sold-spray",
    title: "DEMO: Sold Spray",
    subtitle: null,
    year: 2024,
    medium: "Marker drawings and spray-paint",
    surface: "Board",
    width_cm: 50,
    height_cm: 70,
    description: "Demo sold artwork entry for testing the gallery.",
    price_cents: 27000,
    currency: "EUR",
    status: "sold",
    is_featured: false,
    is_published: true,
    manual_sort_order: 90,
    created_at: now,
    updated_at: now,
    published_at: now,
    reserved_until: null,
    revolut_payment_url: null,
    images: [
      {
        id: "demo-img-9",
        artwork_id: "demo-sold-spray",
        object_key: "/sample-art/demo-night-lines.svg",
        alt_text: "Demo image for a sold artwork listing.",
        caption: "Demo image.",
        width: 1200,
        height: 1400,
        file_type: "image/svg+xml",
        file_size: 2048,
        display_order: 0,
        is_primary: true,
        created_at: now,
      },
    ],
  },
];

export const demoOrders: Order[] = [];
export const demoMessages: ContactMessage[] = [];
export const demoSettings = defaultSiteSettings;
